apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: apps
  sources:
    - repoURL: https://jellyfin.github.io/jellyfin-helm
      chart: jellyfin
      targetRevision: 2.7.0
      helm:
        releaseName: jellyfin
        values: |
          service:
            type: LoadBalancer
            loadBalancerIP: 10.23.45.241

          # Use an existing PVC for config (optional: set this if you created it)
          persistence:
            config:
              enabled: true
              existingClaim: jellyfin-config
            # disable the chart's auto media PVC; we'll mount our own below
            media:
              enabled: false

          # Mount a static PVC at /media
          volumes:
            - name: media
              persistentVolumeClaim:
                claimName: jellyfin-media-pvc
          volumeMounts:
            - name: media
              mountPath: /media
              readOnly: false

          # Run as your jellyfin:media service account
          podSecurityContext:
            fsGroup: 3001
          securityContext:
            runAsUser: 1001
            runAsGroup: 3001
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
