---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-media-pv
  annotations:
    argocd.argoproj.io/tracking-id: jellyfin:v1/PersistentVolume:/jellyfin-media-pv
spec:
  capacity:
    storage: 1Ti
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - vers=4.1
    - hard
    - noatime
  nfs:
    server: 10.23.45.121
    path: /mnt/tank/media
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-pvc
  namespace: jellyfin
  annotations:
    argocd.argoproj.io/tracking-id: jellyfin:/PersistentVolumeClaim/:jellyfin/jellyfin-media-pvc
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: ""
  volumeName: jellyfin-media-pv
  resources:
    requests:
      storage: 500Gi
