# jellyfin-nfs-sc.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-truenas-media
provisioner: nfs.csi.k8s.io
allowVolumeExpansion: true
parameters:
  server: 10.23.45.21
  share: /mnt/tank/media
mountOptions:
  - nfsvers=3
reclaimPolicy: Retain
volumeBindingMode: Immediate
