apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: apps
  sources:
    - repoURL: https://jellyfin.github.io/jellyfin-helm
      chart: jellyfin
      targetRevision: 2.7.0
      helm:
        releaseName: jellyfin
        parameters:
          - name: service.type
            value: LoadBalancer
          - name: service.loadBalancerIP
            value: 10.23.45.241
          - name: persistence.media.existingClaim
            value: jellyfin-media-pvc
          - name: podSecurityContext.fsGroup
            value: "3001"
          - name: podSecurityContext.runAsUser
            value: "1001"
          - name: podSecurityContext.runAsGroup
            value: "3001"
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
