apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-nfs
  namespace: jellyfin
  annotations:
    argocd.argoproj.io/tracking-id: jellyfin:/PersistentVolumeClaim/:jellyfin/jellyfin-media-nfs
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: nfs-truenas-media
  resources:
    requests:
      storage: 500Gi
