apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media-pvc
  namespace: jellyfin
  annotations:
    argocd.argoproj.io/tracking-id: jellyfin:/PersistentVolumeClaim/:jellyfin/jellyfin-media-nfs
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: truenas-nfs-sc
  resources:
    requests:
      storage: 500Gi
