# jellyfin-nfs-sc.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: truenas-nfs-sc
  annotations:
    argocd.argoproj.io/tracking-id: jellyfin:/StorageClass/:jellyfin/nfs-truenas-media
provisioner: nfs.csi.k8s.io
allowVolumeExpansion: true
parameters:
  server: 10.23.45.121
  share: /mnt/tank/media
mountOptions:
  - nfsvers=4.1
  - sec=sys
  - rsize=1048576
  - wsize=1048576
  - hard
  - timeo=600
reclaimPolicy: Retain
volumeBindingMode: Immediate
