apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

patches:
  - path: argocd-cm.yaml
    target:
      kind: ConfigMap
      name: argocd-cm
  - path: argocd-server.yaml
    target:
      kind: Service
      name: argocd-server
